### ISSUE TITLE
gradle dependency are not resolving

### ISSUE THREAD

**Issue by Subhash1987** [OfficeDev/O365-Android-Connect#6] opened 2015-06-15 11:44 UTC
following gradle dependency are not resolving with any of repo jcenter/maven 

    Error:Failed to resolve: com.microsoft.services:odata-engine-core:0.13.0
    Error:Failed to resolve: com.microsoft.services:discovery-services:0.13.0
    Error:Failed to resolve: com.microsoft.services:outlook-services:0.13.0
    Error:Failed to resolve: com.microsoft.services:odata-engine-android-impl:0.13.0

please tell me how to resolve them.

**Comment by Ricalo** [comment] 2015-06-15 15:49
Mmm...I'm not sure what the problem is. Could you check that your root build.gradle file has the following lines?
``
allprojects {
    repositories {
        jcenter()
    }
}
``
MSOpenTech publishes the files here
https://bintray.com/msopentech/Maven/Office-365-SDK-for-Android/0.13.0/view
Please let me know if you are still having dependency issues

**Comment by Ricalo** [comment] 2015-06-15 19:53
Update: @iambmelt just added continuous integration (CI) via Travis and the CI service downloaded all the dependencies with no issues.
Is it possible that this is a connectivity issue between your box and jcenter/maven?
I'm closing this issue, feel free to reopen if you still have problems downloading the dependencies.

**Closed by Ricalo** 2015-06-15 19:53 UTC
