### ISSUE TITLE
AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED

### ISSUE THREAD

**Issue by JorgeRi** [OfficeDev/O365-Android-Connect#2] opened 2015-04-30 09:37 UTC
Hi,
this is the error I get when click to send the email.
Which could be the issue here?

1902-1934/com.microsoft.office365.connect V/AuthenticationContext? 2015-04-30 09:32:37-68c05335-1047-4375-88df-ac63a53ebc79-Sending async task from thread:1934 ver:1.1.2
902-1930/com.microsoft.office365.connect V/AuthenticationContext? 2015-04-30 09:32:37-68c05335-1047-4375-88df-ac63a53ebc79-Running task in thread:1930 ver:1.1.2
1902-1930/com.microsoft.office365.connect V/AuthenticationContext? 2015-04-30 09:32:37-68c05335-1047-4375-88df-ac63a53ebc79-Token request started ver:1.1.2
1902-1930/com.microsoft.office365.connect V/AuthenticationContext? 2015-04-30 09:32:38-68c05335-1047-4375-88df-ac63a53ebc79-Checking refresh tokens ver:1.1.2
1902-1930/com.microsoft.office365.connect V/AuthenticationContext? 2015-04-30 09:32:38-68c05335-1047-4375-88df-ac63a53ebc79-Looking for regular refresh token ver:1.1.2
1902-1930/com.microsoft.office365.connect V/AuthenticationContext? 2015-04-30 09:32:38-68c05335-1047-4375-88df-ac63a53ebc79-Looking for Multi Resource Refresh token ver:1.1.2
1902-1930/com.microsoft.office365.connect V/AuthenticationContext? 2015-04-30 09:32:38-68c05335-1047-4375-88df-ac63a53ebc79-Refresh token is not available ver:1.1.2
1902-1930/com.microsoft.office365.connect E/AuthenticationContext? AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED:2015-04-30 09:32:38-68c05335-1047-4375-88df-ac63a53ebc79-Prompt is not allowed and failed to get token: ver:1.1.2
1902-1934/com.microsoft.office365.connect E/MailController? sendMail - Refresh token is failed and prompt is not allowed
1902-1934/com.microsoft.office365.connect E/SendMailActivity? onSendMailButtonClick - com.microsoft.aad.adal.AuthenticationException: Refresh token is failed and prompt is not allowed

**Comment by iambmelt** [comment] 2015-04-30 16:30
(Condensing)

    <pkg> V/AuthenticationContext? Sending async task from thread:1934 ver:1.1.2
    <pkg> V/AuthenticationContext? Running task in thread:1930 ver:1.1.2
    <pkg> V/AuthenticationContext? Token request started ver:1.1.2
    <pkg> V/AuthenticationContext? Checking refresh tokens ver:1.1.2
    <pkg> V/AuthenticationContext? Looking for regular refresh token ver:1.1.2
    <pkg> V/AuthenticationContext? Looking for Multi Resource Refresh token ver:1.1.2
    <pkg> V/AuthenticationContext? Refresh token is not available ver:1.1.2
    <pkg> E/AuthenticationContext? AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED: Prompt is not allowed and failed to get token: ver:1.1.2
    <pkg> E/MailController? sendMail - Refresh token is failed and prompt is not allowed
    <pkg> E/SendMailActivity? onSendMailButtonClick - com.microsoft.aad.adal.AuthenticationException: Refresh token is failed and prompt is not allowed

**Comment by Ricalo** [comment] 2015-04-30 18:03
Hello Jorge,
I'm sorry you're having problems running the sample.
I'm having a hard time reproducing the problem that you mention. I've seen that error before when the ResourceId is not set to the right value, but this shouldn't be the case if you haven't modified the code.

I'm asking some of my coworkers to try to repro the error that you mention, but in the meantime can you confirm that you're using the following permission in your Azure application?

**Office 365 Exchange Online -> Send mail as a user**

Also, can you share some details about your device or emulator? What API level is it set to?

**Comment by iambmelt** [comment] 2015-04-30 20:52
@Ricalo I've not been able to reproduce this issue locally. 

@JorgeRi In the past, when I experienced this issue it was because the ```DISCOVERY_RESOURCE_ID``` against which I was attempting to authenticate was misconfigured. Do you have a fork of this repo we could test?

**Comment by Ricalo** [comment] 2015-05-05 23:49
Closing this issue due to not having enough details to research possible solution. @JorgeRi, feel free to reopen if you can share something else.

**Closed by Ricalo** 2015-05-05 23:49 UTC
